defmodule OpenAPIClient.GeneratorTest do
  use ExUnit.Case, async: true

  @temp_dir_name_length 16
  @oapi_generator_app :oapi_generator
  @open_api_client_app :open_api_client_ex
  @test_profile :test
  @temp_profile :temp_test
  @lib_dir "lib/open_api_client"
  @test_dir "test/open_api_client"
  @web_dir "test/support/open_api_client_web"
  @web_test_dir "test/open_api_client_web"

  test "check test generation produces the same files" do
    # Generate temporary dir
    tmp_dir =
      @temp_dir_name_length
      |> :crypto.strong_rand_bytes()
      |> Base.url_encode64(padding: false)
      |> then(&Path.join(System.tmp_dir!(), &1))

    # Removing exissting contents (just in case, paranoia)
    File.rm_rf!(tmp_dir)

    # Create dir structure
    File.mkdir!(tmp_dir)

    temp_lib_dir = Path.join(tmp_dir, @lib_dir)
    File.mkdir_p!(temp_lib_dir)

    temp_test_dir = Path.join(tmp_dir, @test_dir)
    File.mkdir_p!(temp_test_dir)

    temp_web_dir = Path.join(tmp_dir, @web_dir)
    File.mkdir_p!(temp_web_dir)

    temp_web_test_dir = Path.join(tmp_dir, @web_test_dir)
    File.mkdir_p!(temp_web_test_dir)

    # Copy existing `router.ex` for generation procedure to be able to change it
    web_dir = OpenAPIClient.Generator.Utils.get_web_location(@test_profile)
    File.cp!(Path.join(web_dir, "router.ex"), Path.join(temp_web_dir, "router.ex"))

    # Redirect generated content to temporary dirs
    oapi_generator_test_config = Application.fetch_env!(@oapi_generator_app, @test_profile)

    oapi_generator_test_config
    |> put_in([:output, :location], temp_lib_dir)
    |> then(&Application.put_env(@oapi_generator_app, @temp_profile, &1))

    open_api_client_test_config = Application.fetch_env!(@open_api_client_app, @test_profile)

    open_api_client_test_config
    |> Keyword.merge(
      aliased_profile: @test_profile,
      test_location: temp_test_dir,
      web_location: temp_web_dir,
      web_test_location: temp_web_test_dir
    )
    |> then(&Application.put_env(@open_api_client_app, @temp_profile, &1))

    # Run generator with temporary profile
    Mix.Task.run("api.gen.proxy", ["#{@temp_profile}", "test/fixture/test.yaml"])

    # Compare files generated by :oapi_generator
    temp_lib_dir
    |> Path.join("**/*.ex")
    |> Path.wildcard()
    |> Enum.each(fn test_filename ->
      relative_filename = Path.relative_to(test_filename, temp_lib_dir)

      real_filename =
        oapi_generator_test_config
        |> get_in([:output, :location])
        |> Path.join(relative_filename)

      assert File.read!(real_filename) == File.read!(test_filename)
    end)

    # Compare test files generated by :open_api_client_ex
    temp_test_dir
    |> Path.join("**/*.exs")
    |> Path.wildcard()
    |> Enum.each(fn test_filename ->
      relative_filename = Path.relative_to(test_filename, temp_test_dir)

      real_filename =
        @test_profile
        |> OpenAPIClient.Generator.Utils.get_test_location()
        |> Path.join(relative_filename)

      assert File.read!(real_filename) == File.read!(test_filename)
    end)

    # Compare web files generated by :open_api_client_ex
    temp_web_dir
    |> Path.join("**/*.ex")
    |> Path.wildcard()
    |> Enum.each(fn test_filename ->
      relative_filename = Path.relative_to(test_filename, temp_web_dir)
      real_filename = Path.join(web_dir, relative_filename)
      assert File.read!(real_filename) == File.read!(test_filename)
    end)

    # Compare web test files generated by :open_api_client_ex
    temp_web_test_dir
    |> Path.join("**/*.exs")
    |> Path.wildcard()
    |> Enum.each(fn test_filename ->
      relative_filename = Path.relative_to(test_filename, temp_web_test_dir)

      real_filename =
        @test_profile
        |> OpenAPIClient.Generator.Utils.get_web_test_location()
        |> Path.join(relative_filename)

      assert File.read!(real_filename) == File.read!(test_filename)
    end)

    # Cleanup / remove temporary dir
    File.rm_rf!(tmp_dir)
  end
end
